#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control gnome
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/${CODENAME_SAFE}-gnome-settings.install \
    > ./debian/${CODENAME_SAFE}-gnome-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/${CODENAME_SAFE}-gnome-settings.postinst \
    > ./debian/${CODENAME_SAFE}-gnome-settings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/${CODENAME_SAFE}-gnome-livesettings.install \
    > ./debian/${CODENAME_SAFE}-gnome-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/${CODENAME_SAFE}-gnome-livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-gnome-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/${CODENAME_SAFE}-gnome-livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-gnome-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/${CODENAME_SAFE}-gnome-settings.prerm \
    > ./debian/${CODENAME_SAFE}-gnome-settings.prerm


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/${CODENAME_SAFE}-gnome-livesettings.service \
    > ./debian/${CODENAME_SAFE}-gnome-livesettings.service

## templating

[ -d ./etc ] && rm -rf ./etc
[ -d ./usr ] && rm -rf ./usr
cp -r ../template/etc .
cp -r ../template/usr .


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/automount-open.desktop \
    > ./automount-open.desktop

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/usr/share/gnome-background-properties/siduction.xml \
    > ./usr/share/gnome-background-properties/siduction.xml

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/usr/share/glib-2.0/schemas/installed/90_org.gnome.desktop.background.gschema.override \
    > ./usr/share/glib-2.0/schemas/installed/90_org.gnome.desktop.background.gschema.override

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/usr/share/glib-2.0/schemas/installed/90_org.gnome.desktop.screensaver.wallpaper.gschema.override \
    > ./usr/share/glib-2.0/schemas/installed/90_org.gnome.desktop.screensaver.wallpaper.gschema.override


grub_template gnome


exit 0
