#!/bin/bash

WALLPAPER=patience
CODENAME_SAFE=patience
CODENAME=Patience
VERSION=2018.1.0
DISTRIBUTION=unstable

FLL_LIVE_USER=siducer

# Gdm3 and Gnome settings
BACKGROUND_RENDERING_OPTION="stretched"
